[project]
name = "burgerking-robinhood"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "selenium>=4.35.0",
    "tqdm>=4.67.1",
    "webdriver-manager>=4.0.2",
]
